#*****************************************************************************************
# Vivado (TM) v2023.1.1 (64-bit)
#
# project.tcl: Tcl script for re-creating project 'NetWavetizer-40_V1'
#
# Generated by Vivado on Thu Apr 09 08:51:52 JST 2026
# IP Build 3900379 on Sat Jun 17 05:28:05 MDT 2023
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp/mii_init.v"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/bus_controller/defBusAddressMap.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/bus_controller/defBusController.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp/defRBCP.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/defResetGen.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/ResetGen.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/EdgeDetector.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/defToplevel.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/JKFF.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/Division10.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/defFlashMemoryProgrammer.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/defSPI_IF.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/SPI_IF.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/FlashMemoryProgrammer.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/gig_ethernet_pcs_pma/GtClockDistributer2.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp/defMiiRstTimer.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp/MiiRstTimer.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp/RbcpCdc.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/defSelfDiagnosisSystem.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/defSemImpl.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/SemImpl.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/SelfDiagnosisSystem.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp/defSiTCP.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp/TCP_sender.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp/global_sitcp_manager.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/toplevel.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/bus_controller/BusController.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/synchronizer.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/LEDModule.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/defLEDModule.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp_bbt/SiTCP_XC7A_32K_BBT_V110.V"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp_bbt/TIMER.v"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp_bbt/WRAP_SiTCP_GMII_XC7A_32K.V"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_common_reset.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_gt_common.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_clocking.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_tx_elastic_buffer.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_reset_sync_ex.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_sync_block_ex.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_resets.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/gig_ethernet_pcs_pma/GbEPcsPma.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/Selector_SPI_Port.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/AD9637SPI.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/defAD9637SPI.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/main/AD_ADC_SPI.v"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc/IserdesImpl.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc/defAD9637Adc.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc/AD9637Adc.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc/defAdcRO.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc/AdcRO.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc/AdcBlock.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc/defAdcBlock.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/daq/defEventBuilder.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/daq/EventBuilder.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/daq/defDAQController.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/daq/DAQController.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/trigger/TriggerManager.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/trigger/defTriggerManager.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc_trigger/TriggerGen.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc_trigger/defTriggerGen.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc_trigger/AdcTrigger.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc_trigger/Discriminator.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc_trigger/defSelfVETO.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc_trigger/TriggerDelay.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc_trigger/defAdcTrigger.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc_trigger/SelfVETO.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/adc_trigger/EdgeCounter.vhd"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/hdl/sitcp_bbt/SiTCP_XC7A_32K_BBT_V110.edf"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/RbcpCdc_LinkToSys/RbcpCdc_LinkToSys.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/xadc_sys/xadc_sys.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/RbcpCdc_SysToLink/RbcpCdc_SysToLink.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/fmp_wd_fifo/fmp_wd_fifo.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/fmp_rd_fifo/fmp_rd_fifo.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/sem_controller/sem_controller.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/clk_wiz_sys/clk_wiz_sys.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/vio_adc/vio_adc.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/adc_cdc_fifo/adc_cdc_fifo.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/ringbuffer_adc/ringbuffer_adc.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/evsummary_fifo/evsummary_fifo.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/event_buffer/event_buffer.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/channel_buffer_adc/channel_buffer_adc.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/block_buffer_adc/block_buffer_adc.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/sub_event_buffer/sub_event_buffer.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/sources_1/ip/trigger_record_fifo/trigger_record_fifo.xci"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/constrs_1/new/pins.xdc"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/constrs_1/new/gig_ethernet.xdc"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/constrs_1/new/timing.xdc"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/constrs_1/new/impl.xdc"
#    "/home/mizoguchi/FW_Develop/NetWavetizer-40_V1/utils_1/imports/synth_1/toplevel.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/sources_1/hdl/sitcp/mii_init.v"]"\
 "[file normalize "$origin_dir/sources_1/hdl/bus_controller/defBusAddressMap.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/bus_controller/defBusController.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp/defRBCP.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/defResetGen.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/ResetGen.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/EdgeDetector.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/defToplevel.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/JKFF.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/Division10.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/defFlashMemoryProgrammer.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/defSPI_IF.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/SPI_IF.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/FlashMemoryProgrammer.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/gig_ethernet_pcs_pma/GtClockDistributer2.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp/defMiiRstTimer.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp/MiiRstTimer.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp/RbcpCdc.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/defSelfDiagnosisSystem.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/defSemImpl.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/SemImpl.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/SelfDiagnosisSystem.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp/defSiTCP.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp/TCP_sender.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp/global_sitcp_manager.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/toplevel.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/bus_controller/BusController.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/synchronizer.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/LEDModule.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/defLEDModule.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp_bbt/SiTCP_XC7A_32K_BBT_V110.V"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp_bbt/TIMER.v"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp_bbt/WRAP_SiTCP_GMII_XC7A_32K.V"]"\
 "[file normalize "$origin_dir/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_common_reset.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_gt_common.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_clocking.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_tx_elastic_buffer.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_reset_sync_ex.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_sync_block_ex.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_resets.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/gig_ethernet_pcs_pma/GbEPcsPma.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/Selector_SPI_Port.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/AD9637SPI.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/defAD9637SPI.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/main/AD_ADC_SPI.v"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc/IserdesImpl.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc/defAD9637Adc.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc/AD9637Adc.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc/defAdcRO.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc/AdcRO.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc/AdcBlock.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc/defAdcBlock.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/daq/defEventBuilder.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/daq/EventBuilder.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/daq/defDAQController.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/daq/DAQController.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/trigger/TriggerManager.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/trigger/defTriggerManager.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc_trigger/TriggerGen.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc_trigger/defTriggerGen.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc_trigger/AdcTrigger.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc_trigger/Discriminator.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc_trigger/defSelfVETO.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc_trigger/TriggerDelay.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc_trigger/defAdcTrigger.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc_trigger/SelfVETO.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/adc_trigger/EdgeCounter.vhd"]"\
 "[file normalize "$origin_dir/sources_1/hdl/sitcp_bbt/SiTCP_XC7A_32K_BBT_V110.edf"]"\
 "[file normalize "$origin_dir/sources_1/ip/RbcpCdc_LinkToSys/RbcpCdc_LinkToSys.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/xadc_sys/xadc_sys.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/RbcpCdc_SysToLink/RbcpCdc_SysToLink.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/fmp_wd_fifo/fmp_wd_fifo.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/fmp_rd_fifo/fmp_rd_fifo.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/sem_controller/sem_controller.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/clk_wiz_sys/clk_wiz_sys.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/vio_adc/vio_adc.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/adc_cdc_fifo/adc_cdc_fifo.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/ringbuffer_adc/ringbuffer_adc.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/evsummary_fifo/evsummary_fifo.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/event_buffer/event_buffer.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/channel_buffer_adc/channel_buffer_adc.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/block_buffer_adc/block_buffer_adc.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/sub_event_buffer/sub_event_buffer.xci"]"\
 "[file normalize "$origin_dir/sources_1/ip/trigger_record_fifo/trigger_record_fifo.xci"]"\
 "[file normalize "$origin_dir/constrs_1/new/pins.xdc"]"\
 "[file normalize "$origin_dir/constrs_1/new/gig_ethernet.xdc"]"\
 "[file normalize "$origin_dir/constrs_1/new/timing.xdc"]"\
 "[file normalize "$origin_dir/constrs_1/new/impl.xdc"]"\
 "[file normalize "$origin_dir/utils_1/imports/synth_1/toplevel.dcp"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "NetWavetizer-40_V1"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a100tfgg484-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "mylib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7a100tfgg484-1" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "source_mgmt_mode" -value "DisplayOnly" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "109" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "109" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "109" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "109" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "109" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "109" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/hdl/sitcp/mii_init.v" ]\
 [file normalize "${origin_dir}/sources_1/hdl/bus_controller/defBusAddressMap.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/bus_controller/defBusController.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp/defRBCP.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/defResetGen.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/ResetGen.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/EdgeDetector.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/defToplevel.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/JKFF.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/Division10.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/defFlashMemoryProgrammer.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/defSPI_IF.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/SPI_IF.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/FlashMemoryProgrammer.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/gig_ethernet_pcs_pma/GtClockDistributer2.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp/defMiiRstTimer.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp/MiiRstTimer.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp/RbcpCdc.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/defSelfDiagnosisSystem.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/defSemImpl.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/SemImpl.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/SelfDiagnosisSystem.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp/defSiTCP.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp/TCP_sender.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp/global_sitcp_manager.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/toplevel.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/bus_controller/BusController.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/synchronizer.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/LEDModule.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/defLEDModule.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp_bbt/SiTCP_XC7A_32K_BBT_V110.V" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp_bbt/TIMER.v" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp_bbt/WRAP_SiTCP_GMII_XC7A_32K.V" ]\
 [file normalize "${origin_dir}/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_common_reset.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_gt_common.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_clocking.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_tx_elastic_buffer.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_reset_sync_ex.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_sync_block_ex.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_resets.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/gig_ethernet_pcs_pma/GbEPcsPma.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/Selector_SPI_Port.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/AD9637SPI.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/defAD9637SPI.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/main/AD_ADC_SPI.v" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc/IserdesImpl.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc/defAD9637Adc.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc/AD9637Adc.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc/defAdcRO.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc/AdcRO.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc/AdcBlock.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc/defAdcBlock.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/daq/defEventBuilder.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/daq/EventBuilder.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/daq/defDAQController.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/daq/DAQController.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/trigger/TriggerManager.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/trigger/defTriggerManager.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc_trigger/TriggerGen.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc_trigger/defTriggerGen.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc_trigger/AdcTrigger.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc_trigger/Discriminator.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc_trigger/defSelfVETO.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc_trigger/TriggerDelay.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc_trigger/defAdcTrigger.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc_trigger/SelfVETO.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/adc_trigger/EdgeCounter.vhd" ]\
 [file normalize "${origin_dir}/sources_1/hdl/sitcp_bbt/SiTCP_XC7A_32K_BBT_V110.edf" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "sitcp/mii_init.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "bus_controller/defBusAddressMap.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "bus_controller/defBusController.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp/defRBCP.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/defResetGen.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/ResetGen.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/EdgeDetector.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/defToplevel.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/JKFF.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/Division10.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/defFlashMemoryProgrammer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/defSPI_IF.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/SPI_IF.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/FlashMemoryProgrammer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "gig_ethernet_pcs_pma/GtClockDistributer2.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp/defMiiRstTimer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp/MiiRstTimer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp/RbcpCdc.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/defSelfDiagnosisSystem.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/defSemImpl.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/SemImpl.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/SelfDiagnosisSystem.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp/defSiTCP.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp/TCP_sender.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp/global_sitcp_manager.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "hdl/toplevel.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "bus_controller/BusController.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/synchronizer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/LEDModule.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/defLEDModule.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp_bbt/SiTCP_XC7A_32K_BBT_V110.V"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp_bbt/TIMER.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp_bbt/WRAP_SiTCP_GMII_XC7A_32K.V"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_common_reset.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_gt_common.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_clocking.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_tx_elastic_buffer.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_reset_sync_ex.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_sync_block_ex.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "gig_ethernet_pcs_pma/gig_ethernet_pcs_pma_resets.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "gig_ethernet_pcs_pma/GbEPcsPma.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/Selector_SPI_Port.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/AD9637SPI.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/defAD9637SPI.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "main/AD_ADC_SPI.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc/IserdesImpl.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc/defAD9637Adc.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc/AD9637Adc.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc/defAdcRO.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc/AdcRO.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc/AdcBlock.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc/defAdcBlock.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "daq/defEventBuilder.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "daq/EventBuilder.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "daq/defDAQController.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "daq/DAQController.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "trigger/TriggerManager.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "trigger/defTriggerManager.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc_trigger/TriggerGen.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc_trigger/defTriggerGen.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc_trigger/AdcTrigger.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc_trigger/Discriminator.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc_trigger/defSelfVETO.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc_trigger/TriggerDelay.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc_trigger/defAdcTrigger.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc_trigger/SelfVETO.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "adc_trigger/EdgeCounter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "sitcp_bbt/SiTCP_XC7A_32K_BBT_V110.edf"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "EDIF" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "toplevel" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/RbcpCdc_LinkToSys/RbcpCdc_LinkToSys.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "RbcpCdc_LinkToSys/RbcpCdc_LinkToSys.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/xadc_sys/xadc_sys.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "xadc_sys/xadc_sys.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/RbcpCdc_SysToLink/RbcpCdc_SysToLink.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "RbcpCdc_SysToLink/RbcpCdc_SysToLink.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/fmp_wd_fifo/fmp_wd_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fmp_wd_fifo/fmp_wd_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/fmp_rd_fifo/fmp_rd_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fmp_rd_fifo/fmp_rd_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "is_enabled" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/sem_controller/sem_controller.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "sem_controller/sem_controller.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/clk_wiz_sys/clk_wiz_sys.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "clk_wiz_sys/clk_wiz_sys.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/vio_adc/vio_adc.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "vio_adc/vio_adc.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/adc_cdc_fifo/adc_cdc_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "adc_cdc_fifo/adc_cdc_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/gig_ethernet_pcs_pma/gig_ethernet_pcs_pma.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "gig_ethernet_pcs_pma/gig_ethernet_pcs_pma.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/ringbuffer_adc/ringbuffer_adc.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "ringbuffer_adc/ringbuffer_adc.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/evsummary_fifo/evsummary_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "evsummary_fifo/evsummary_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/event_buffer/event_buffer.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "event_buffer/event_buffer.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/channel_buffer_adc/channel_buffer_adc.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "channel_buffer_adc/channel_buffer_adc.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/block_buffer_adc/block_buffer_adc.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "block_buffer_adc/block_buffer_adc.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/sub_event_buffer/sub_event_buffer.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "sub_event_buffer/sub_event_buffer.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/sources_1/ip/trigger_record_fifo/trigger_record_fifo.xci" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "trigger_record_fifo/trigger_record_fifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs_1/new/pins.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "new/pins.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs_1/new/gig_ethernet.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "new/gig_ethernet.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs_1/new/timing.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "new/timing.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs_1/new/impl.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "new/impl.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[get_files *new/impl.xdc]" -objects $obj
set_property -name "target_part" -value "xc7a100tfgg484-1" -objects $obj
set_property -name "target_ucf" -value "[get_files *new/impl.xdc]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "toplevel" -objects $obj
set_property -name "top_lib" -value "mylib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/utils_1/imports/synth_1/toplevel.dcp" ]\
]
set imported_files [import_files -fileset utils_1 $files]

# Set 'utils_1' fileset file properties for remote files
# None

# Set 'utils_1' fileset file properties for local files
set file "synth_1/toplevel.dcp"
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "netlist_only" -value "0" -objects $file_obj


# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a100tfgg484-1 -flow {Vivado Synthesis 2023} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2023" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7a100tfgg484-1" -objects $obj
#set_property -name "incremental_checkpoint" -value "$proj_dir/utils_1/imports/synth_1/toplevel.dcp" -objects $obj
set_property -name "incremental_checkpoint" -value "$origin_dir/utils_1/imports/synth_1/toplevel.dcp" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a100tfgg484-1 -flow {Vivado Implementation 2023} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2023" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "part" -value "xc7a100tfgg484-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
